name: possys
recipe: lamp
proxy:
  pma:
    - possysmyadmin.lndo.site
services:
  appserver:
    type: php:7.2
    webroot: public
    config:
      conf: config/php.ini
    xdebug: true

  database:
    type: mariadb:10.1

  pma:
    type: phpmyadmin
